#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "mmm.h"

/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init()
{
	int i;

	 A = (double**)malloc(size*sizeof(double*));
	for(i=0;i<size;i++){
		A[i]=(double*)malloc(size*sizeof(double));
	}
	
	B = (double**)malloc(size*sizeof(double*));
	for(i=0;i<size;i++){
		B[i]=(double*)malloc(size*sizeof(double));
	}

	C = (double**)malloc(size*sizeof(double*));
	for(i=0;i<size;i++){
		C[i]=(double*)malloc(size*sizeof(double));
	}
	
	D = (double**)malloc(size*sizeof(double*));
	for(i=0;i<size;i++){
		D[i]=(double*)malloc(size*sizeof(double));
	}  

	int j;
    srand(time(NULL));
  	for(i = 0; i < size; i++){
		for (j = 0; j < size; j++){
			A[i][j]=(double)(rand() % 100);
			B[i][j]=(double)(rand() % 100);
		}
			
	} 
}


/**
 * Reset a given matrix to zeroes
 * @param matrix pointer to a 2D array
 */
void mmm_reset(double **matrix)
{
	for	(int i = 0; i < size; i++){
		for (int j = 0; j < size; j++){
			matrix[i][j]=0;
		}
			
	}
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup()
{
	int i;
	for	(i = 0; i < size; i++){
		free(A[i]);
	}
	free(A);
	for	(i = 0; i < size; i++){
		free(B[i]);
	}
	free(B);
	for	(i = 0; i < size; i++){
		free(C[i]);
	}
	free(C);
	for	(i = 0; i < size; i++){
		free(D[i]);
	}
	free(D);
}

/**
 * Sequential MMM
 */
void mmm_seq()
{
	for	(int i = 0; i < size; i++){
		for (int j = 0; j < size; j++){
			for(int k=0; k<size; k++){
				C[i][j]+=(A[i][k])*(B[k][j]);
			}
		}		
	}
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args)
{
	struct parParams *params = (struct parParams *) args;
	int s_row = params->s_row;
	int f_row = params->f_row;

	for	(int i = s_row; i < f_row+1; i++){
		for (int j = 0; j < size; j++){
			for(int k=0; k<size; k++){
				D[i][j]+=(A[i][k])*(B[k][j]);
			}
		}		
	}
	return NULL;
}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 * in the result matrices
 */
double mmm_verify()
{
	double largest;
	double diff;
	for	(int i = 0; i < size; i++){
		for (int j = 0; j < size; j++){
			diff=abs((C[i][j])-(D[i][j]));
			if(largest<diff){
				largest=diff;
			}
		}		
	}
	return largest;
}

/**
 * Prints a given matrix
 * @param matrix pointer to a 2D array
 */
void printMatrix(double **matrix)
{
	double p;
	for	(int i = 0; i < size; i++){
		for (int j = 0; j < size; j++){
			p = matrix[i][j];
			printf("[%f]",p);
		}
		printf("\n");	
	}
}
